name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore      

    - name: publish
      run: dotnet publish -r win-x64 Release /p:PublishSingleFile=true
